//! The Adventure arrangement selector: the default eight-section output, and
//! an opt-in composed path that builds a [`SongForm`] over the phase pool.

use crate::score::{MusicEvent, PortableScore, PortableSection};

use super::pool::{
    adventure_compose, adventure_compose_seed, adventure_phase_bars, adventure_phase_spec,
};
use super::{generate_adventure, AdventureInput};

/// Version of the composed-arrangement wrapper itself.
pub const COMPOSED_VERSION: &str = "1";

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum AdventureArrangement {
    #[default]
    Original,
    Composed,
}

impl AdventureArrangement {
    pub fn parse(value: &str) -> Result<Self, String> {
        match value {
            "" | "original" => Ok(Self::Original),
            "composed" => Ok(Self::Composed),
            other => Err(format!("Unknown adventure arrangement: {other}")),
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Original => "original",
            Self::Composed => "composed",
        }
    }
}

pub fn generate_adventure_arrangement(
    input: &AdventureInput,
    arrangement: AdventureArrangement,
) -> Result<PortableScore, String> {
    match arrangement {
        AdventureArrangement::Original => generate_adventure(input),
        AdventureArrangement::Composed => generate_composed(input),
    }
}

/// Compose an Adventure song form over the eight-section pool, mirroring
/// Racing's pool + composer: role/energy metadata (derived from the authored
/// plans) feeds a seeded composer that picks a legal quest order and a groove
/// loop point, and role-aware lengths re-time the sections (peaks and grooves
/// longer, intro/break/outro at their authored length). The eight base sections
/// are generated by [`generate_adventure`] unchanged; only their lengths, the
/// form and the score's id/title differ.
fn generate_composed(input: &AdventureInput) -> Result<PortableScore, String> {
    let mut score = generate_adventure(input)?;
    let bar = score.bar_ticks();
    let form_seed = adventure_compose_seed(&input.secret, &input.seed);

    // Re-time by role before composing the form so each step references the
    // final length. Sections not chosen by the composer still re-time; they are
    // carried in the score but simply not toured.
    for section in &mut score.sections {
        let Some(spec) = adventure_phase_spec(&section.id) else {
            continue;
        };
        let bars = adventure_phase_bars(&spec, form_seed);
        if bars * bar != section.length_ticks {
            retime_section(section, bars, bar);
        }
    }

    score.form = Some(adventure_compose(form_seed));

    score.id.push_str(&format!("-composed-v{COMPOSED_VERSION}"));
    score.title.push_str(" — Composed");
    score.validate()?;
    Ok(score)
}

/// Re-time a section to `bars` by tiling its authored block. Every event keeps
/// its lane, voice, pitch and role; only its id and onset change, so the score
/// stays valid and every event id stays unique.
fn retime_section(section: &mut PortableSection, bars: u32, bar_ticks: u32) {
    let src_len = section.length_ticks;
    if src_len == 0 {
        return;
    }
    let target = bars * bar_ticks;
    let src_events = std::mem::take(&mut section.events);
    let mut out = Vec::new();
    let mut block = 0u32;
    while block * src_len < target {
        let offset = block * src_len;
        for event in &src_events {
            let start = event.start_tick() + offset;
            if start >= target {
                continue;
            }
            let dur = event.duration_ticks().min(target - start);
            let mut event = event.clone();
            match &mut event {
                MusicEvent::Note {
                    id,
                    start_tick,
                    duration_ticks,
                    ..
                }
                | MusicEvent::Percussion {
                    id,
                    start_tick,
                    duration_ticks,
                    ..
                } => {
                    *id = format!("{id}:t{block}");
                    *start_tick = start;
                    *duration_ticks = dur;
                }
            }
            out.push(event);
        }
        block += 1;
    }
    section.events = out;
    section.length_ticks = target;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adventure::AdventureStyle;
    use crate::score::MusicEvent;
    use std::collections::HashSet;

    fn sample(secret: &str, style: AdventureStyle) -> AdventureInput {
        AdventureInput {
            secret: secret.into(),
            seed: "trail-01".into(),
            style,
            wonder: 0.6,
            danger: 0.5,
            mystery: 0.6,
            motion: 0.58,
        }
    }

    #[test]
    fn parse_as_str_default_contract() {
        assert_eq!(
            AdventureArrangement::parse("").unwrap(),
            AdventureArrangement::Original
        );
        assert_eq!(
            AdventureArrangement::parse("original").unwrap(),
            AdventureArrangement::Original
        );
        assert_eq!(
            AdventureArrangement::parse("composed").unwrap(),
            AdventureArrangement::Composed
        );
        assert!(AdventureArrangement::parse("foo").is_err());
        assert!(AdventureArrangement::parse("Original").is_err());
        assert_eq!(AdventureArrangement::Original.as_str(), "original");
        assert_eq!(AdventureArrangement::Composed.as_str(), "composed");
        assert_eq!(
            AdventureArrangement::default(),
            AdventureArrangement::Original
        );
    }

    #[test]
    fn original_delegates_unchanged() {
        for style in [
            AdventureStyle::Folk,
            AdventureStyle::Dark,
            AdventureStyle::Orchestral,
        ] {
            let input = sample("orig-delegates", style);
            let via =
                generate_adventure_arrangement(&input, AdventureArrangement::Original).expect("via");
            let direct = generate_adventure(&input).expect("direct");
            assert_eq!(
                serde_json::to_vec(&via).expect("ser"),
                serde_json::to_vec(&direct).expect("ser"),
                "{style:?}"
            );
        }
    }

    #[test]
    fn composed_produces_a_valid_score_with_a_real_form() {
        let input = sample("composed-shape", AdventureStyle::Folk);
        let score =
            generate_adventure_arrangement(&input, AdventureArrangement::Composed).expect("composed");
        assert_eq!(score.sections.len(), 8);
        let form = score.form.as_ref().expect("composed must carry a form");
        assert!(!form.steps.is_empty());
        for step in &form.steps {
            assert!(
                score.section(&step.section).is_some(),
                "unknown {}",
                step.section
            );
        }
        if let Some(loop_from) = form.loop_from {
            assert!(loop_from < form.steps.len() as u32);
        }
        assert!(score.id.ends_with(&format!("-composed-v{COMPOSED_VERSION}")));
        assert!(score.title.contains(" — Composed"));
    }

    #[test]
    fn composed_form_starts_camp_ends_victory_and_loops_to_a_groove() {
        let input = sample("composed-frame", AdventureStyle::Folk);
        let score =
            generate_adventure_arrangement(&input, AdventureArrangement::Composed).expect("composed");
        let form = score.form.as_ref().expect("form");
        let loop_from = form.loop_from.expect("composed form must have a loopFrom");
        assert!((loop_from as usize) < form.steps.len());
        assert_eq!(form.steps.first().unwrap().section, "camp");
        assert_eq!(form.steps.last().unwrap().section, "victory");
        let loop_section = &form.steps[loop_from as usize].section;
        assert!(
            loop_section == "explore" || loop_section == "town",
            "loop point must target a groove, got {loop_section}"
        );
    }

    #[test]
    fn composed_role_aware_lengths_stretch_only_the_middle() {
        let input = sample("composed-lengths", AdventureStyle::Folk);
        let score =
            generate_adventure_arrangement(&input, AdventureArrangement::Composed).expect("composed");
        let bar = score.bar_ticks();
        for id in [
            "camp",
            "explore",
            "town",
            "dungeon",
            "combat",
            "boss",
            "sanctuary",
            "victory",
        ] {
            let sec = score.section(id).expect(id);
            let bars = sec.length_ticks / bar;
            assert_eq!(bars % 16, 0, "{id} length not block-aligned");
            match id {
                "camp" | "sanctuary" => {
                    assert_eq!(bars, 16, "{id} should stay at 16");
                }
                "victory" => assert_eq!(bars, 32, "{id} should stay at its authored 32"),
                "explore" | "town" | "combat" => {
                    assert!((32..=48).contains(&bars), "{id} bars {bars}");
                }
                "dungeon" | "boss" => assert!((16..=32).contains(&bars), "{id} bars {bars}"),
                _ => unreachable!(),
            }
        }
    }

    #[test]
    fn composed_event_ids_unique_and_in_bounds() {
        let input = sample("composed-bounds", AdventureStyle::Folk);
        let score =
            generate_adventure_arrangement(&input, AdventureArrangement::Composed).expect("composed");
        let mut seen = HashSet::new();
        for sec in &score.sections {
            for ev in &sec.events {
                let id = match ev {
                    MusicEvent::Note { id, .. } | MusicEvent::Percussion { id, .. } => id,
                };
                assert!(seen.insert(id.clone()), "duplicate event id {}", id);
                assert!(
                    ev.start_tick() + ev.duration_ticks() <= sec.length_ticks,
                    "oob {}",
                    id
                );
            }
        }
    }

    #[test]
    fn composed_is_deterministic_and_varies_by_seed() {
        let i1 = sample("comp-det", AdventureStyle::Folk);
        let mut i2 = i1.clone();
        i2.seed = "trail-02".to_string();
        let s1 = generate_adventure_arrangement(&i1, AdventureArrangement::Composed).expect("s1");
        let s1b = generate_adventure_arrangement(&i1, AdventureArrangement::Composed).expect("s1b");
        let s2 = generate_adventure_arrangement(&i2, AdventureArrangement::Composed).expect("s2");
        assert_eq!(
            serde_json::to_vec(&s1).expect("s1s"),
            serde_json::to_vec(&s1b).expect("s1bs")
        );
        assert_ne!(s1.id, s2.id);
        assert_ne!(
            serde_json::to_vec(&s1).expect("s1s"),
            serde_json::to_vec(&s2).expect("s2s"),
            "a seed must change the composed score, not only the id"
        );
    }

    #[test]
    fn composed_form_varies_across_seeds() {
        let mut forms = HashSet::new();
        for i in 0..16 {
            let mut input = sample("comp-var", AdventureStyle::Folk);
            input.seed = format!("trail-var-{i}");
            let score =
                generate_adventure_arrangement(&input, AdventureArrangement::Composed).expect("ok");
            let steps: Vec<String> = score
                .form
                .expect("form")
                .steps
                .iter()
                .map(|step| step.section.clone())
                .collect();
            forms.insert(steps);
        }
        assert!(forms.len() > 1, "composed form must vary with seed");
    }

    #[test]
    fn composed_leaves_original_untouched() {
        for style in [
            AdventureStyle::Folk,
            AdventureStyle::Dark,
            AdventureStyle::Orchestral,
        ] {
            let input = sample("comp-iso", style);
            let original = generate_adventure(&input).expect("orig");
            let composed =
                generate_adventure_arrangement(&input, AdventureArrangement::Composed).expect("comp");
            assert_eq!(
                serde_json::to_vec(&generate_adventure(&input).expect("orig-again")).expect("o"),
                serde_json::to_vec(&original).expect("o2")
            );
            assert!(composed.form.is_some());
            assert_ne!(composed.id, original.id);
        }
    }
}
