import type { AuthoringScore } from "./export-score.js";

export const pocketCircuitRules = [
  {
    target: "victory",
    priority: 100,
    when: { categorical: { racePhase: "finish", finishResult: "win" } },
  },
  {
    target: "final-lap",
    priority: 90,
    when: { numeric: { finalLap: { min: 1 } } },
  },
  {
    target: "attack",
    priority: 80,
    when: { numeric: { positionPressure: { min: 0.68 } } },
  },
  {
    target: "attack",
    priority: 70,
    when: { numeric: { intensity: { min: 0.72 } } },
  },
  {
    target: "cruise",
    priority: 30,
    when: { categorical: { racePhase: "race" } },
  },
  {
    target: "grid",
    priority: 20,
    when: { categorical: { racePhase: "grid" } },
  },
  {
    target: "garage",
    priority: 10,
    when: { categorical: { racePhase: "garage" } },
  },
] satisfies AuthoringScore["rules"];

export const pocketCircuitScore = {
  id: "pocket-circuit-kitchen-run",
  title: "Countertop Velocity",
  bpm: 126,
  beatsPerBar: 4,
  ticksPerBeat: 960,
  crossfadeBars: 2,
  defaultSection: "garage",
  sections: [
    {
      id: "garage",
      label: "Garage",
      feeling: "polished / unhurried",
      color: "#dbc89a",
      bars: 4,
      lanes: [
        {
          kind: "note",
          id: "electric-keys",
          pattern: "<[d3,f3,a3] [c3,e3,g3] [bb2,d3,f3] [a2,c3,e3]>",
          voice: "warm",
          velocity: 0.42,
          gate: 0.92,
        },
        {
          kind: "note",
          id: "garage-melody",
          pattern: "<[~ ~ ~ d5 ~ ~ ~ f5] [~ ~ ~ g5 ~ ~ ~ e5] [~ ~ ~ c6 ~ ~ ~ e5] [~ ~ ~ a5 ~ ~ ~ c5]>",
          voice: "epiano",
          role: "melody",
          velocity: 0.48,
          gate: 0.78,
        },
        {
          kind: "note",
          id: "soft-bass",
          pattern: "<[d2 ~ a1 ~] [c2 ~ g1 ~] [bb1 ~ f1 ~] [a1 ~ e2 ~]>",
          voice: "bass",
          velocity: 0.48,
          gate: 0.9,
        },
        {
          kind: "percussion",
          id: "brush-kit",
          pattern: "kick ~ hat ~",
          velocity: 0.28,
        },
      ],
      stemMarkers: [{ lane: "room", asset: "kitchen-garage-room.ogg" }],
    },
    {
      id: "grid",
      label: "Starting Grid",
      feeling: "focus / anticipation",
      color: "#f4b740",
      bars: 4,
      lanes: [
        {
          kind: "note",
          id: "grid-chords",
          pattern: "<[d3,f3,a3] [c3,e3,g3] [bb2,d3,f3] [c3,e3,a3]>",
          voice: "warm",
          velocity: 0.46,
          gate: 0.94,
        },
        {
          kind: "note",
          id: "countdown-pulse",
          pattern: "<[~ ~ d5 ~ ~ f5 ~ ~] [~ ~ g5 ~ ~ bb5 ~ ~] [~ ~ c6 ~ ~ e5 ~ ~] [~ ~ a5 ~ ~ c5 ~ e4]>",
          voice: "epiano",
          role: "melody",
          velocity: 0.52,
          gate: 0.58,
        },
        {
          kind: "note",
          id: "grid-bass",
          pattern: "<[d2 ~ a1 ~] [c2 ~ g1 ~] [bb1 ~ f1 ~] [c2 ~ g1 ~]>",
          voice: "bass",
          velocity: 0.58,
          gate: 0.8,
        },
        {
          kind: "percussion",
          id: "grid-kit",
          pattern: "kick hat snare hat kick hat snare [hat hat]",
          velocity: 0.48,
        },
      ],
    },
    {
      id: "cruise",
      label: "Race Flow",
      feeling: "precision / forward motion",
      color: "#73d7c7",
      bars: 4,
      lanes: [
        {
          kind: "note",
          id: "fusion-chords",
          pattern: "<[d3,f3,a3] [g3,bb3,d4] [c3,e3,g3] [a2,c3,e3]>",
          voice: "warm",
          velocity: 0.48,
          gate: 0.88,
        },
        {
          kind: "note",
          id: "race-melody",
          pattern: "<[~ ~ d5 ~ ~ f5 ~ ~] [~ ~ g5 ~ ~ bb5 ~ ~] [~ ~ c6 ~ ~ e5 ~ ~] [~ ~ a5 ~ ~ c5 ~ ~]>",
          voice: "epiano",
          role: "melody",
          velocity: 0.6,
          gate: 0.65,
        },
        {
          kind: "note",
          id: "race-bass",
          pattern: "<[d2 ~ a1 ~] [g2 ~ d2 ~] [c2 ~ g1 ~] [a1 ~ e2 ~]>",
          voice: "bass",
          velocity: 0.68,
          gate: 0.82,
        },
        {
          kind: "percussion",
          id: "race-kit",
          pattern: "kick hat snare hat kick [hat hat] snare hat",
          velocity: 0.62,
        },
      ],
    },
    {
      id: "attack",
      label: "Position Fight",
      feeling: "pressure / resolve",
      color: "#f06c4f",
      bars: 4,
      lanes: [
        {
          kind: "note",
          id: "attack-chords",
          pattern: "<[d3,f3,a3] [eb3,g3,bb3] [c3,e3,g3] [a2,c3,f3]>",
          voice: "organ",
          velocity: 0.53,
          gate: 0.78,
        },
        {
          kind: "note",
          id: "attack-lead",
          pattern: "<[~ ~ d5 ~ ~ ~ eb5 ~] [~ f5 ~ ~ ~ ~ g5 ~] [~ ~ c6 ~ ~ ~ eb5 ~] [~ ~ eb5 ~ ~ ~ ~ c5]>",
          voice: "epiano",
          role: "melody",
          velocity: 0.68,
          gate: 0.5,
        },
        {
          kind: "note",
          id: "attack-bass",
          pattern: "<[d2 ~ a1 ~] [eb2 ~ bb1 ~] [c2 ~ g1 ~] [a1 ~ f2 ~]>",
          voice: "bass",
          velocity: 0.8,
          gate: 0.6,
        },
        {
          kind: "percussion",
          id: "attack-kit",
          pattern: "kick [hat hat] snare hat kick [kick hat] snare [hat hat]",
          velocity: 0.74,
        },
      ],
    },
    {
      id: "final-lap",
      label: "Final Lap",
      feeling: "maximum commitment",
      color: "#ef3f50",
      bars: 4,
      lanes: [
        {
          kind: "note",
          id: "final-chords",
          pattern: "<[d3,f3,a3] [c3,e3,g3] [bb2,d3,f3] [a2,c#3,e3]>",
          voice: "organ",
          velocity: 0.62,
          gate: 0.8,
        },
        {
          kind: "note",
          id: "final-lead",
          pattern: "<[~ ~ d5 ~ ~ f5 ~ ~] [~ ~ g5 ~ ~ bb5 ~ ~] [~ ~ c6 ~ ~ e6 ~ ~] [~ ~ a5 ~ ~ e5?0.5 ~ c#5]>",
          voice: "epiano",
          role: "melody",
          velocity: 0.75,
          gate: 0.55,
        },
        {
          kind: "note",
          id: "final-bass",
          pattern: "<[d2 ~ a1 ~] [c2 ~ g1 ~] [bb1 ~ f1 ~] [a1 ~ e2 ~]>",
          voice: "bass",
          velocity: 0.88,
          gate: 0.6,
        },
        {
          kind: "percussion",
          id: "final-kit",
          pattern: "kick [hat hat] snare [hat hat] [kick kick] hat snare [hat hat]",
          velocity: 0.88,
        },
      ],
      stemMarkers: [{ lane: "final-lap-lift", asset: "final-lap-layer.ogg" }],
    },
    {
      id: "victory",
      label: "Finish",
      feeling: "release / earned confidence",
      color: "#e7d46a",
      bars: 4,
      lanes: [
        {
          kind: "note",
          id: "victory-chords",
          pattern: "<[d3,f#3,a3] [g3,b3,d4] [e3,g3,b3] [a2,c#3,e3]>",
          voice: "warm",
          velocity: 0.58,
          gate: 0.95,
        },
        {
          kind: "note",
          id: "victory-melody",
          pattern: "<[~ ~ d5 ~ ~ f#5 ~ ~] [~ ~ g5 ~ ~ b5 ~ ~] [~ ~ e5 ~ ~ g5 ~ ~] [~ ~ a5 ~ ~ c#5 ~ ~]>",
          voice: "epiano",
          role: "melody",
          velocity: 0.65,
          gate: 0.72,
        },
        {
          kind: "note",
          id: "victory-bass",
          pattern: "<[d2 ~ f#1 ~] [g2 ~ b1 ~] [e2 ~ g1 ~] [a1 ~ c#2 ~]>",
          voice: "bass",
          velocity: 0.62,
          gate: 0.82,
        },
        {
          kind: "percussion",
          id: "victory-kit",
          pattern: "kick hat snare hat kick hat snare [tom tom]",
          velocity: 0.58,
        },
      ],
    },
  ],
  rules: pocketCircuitRules,
} satisfies AuthoringScore;
